const rando = arr => {
  return arr[Math.floor(Math.random() * arr.length)];
};

const slugify = text => {
  return text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]+/g, "")
    .replace(/--+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");
};

const getFunName = () => {
  const adjectives = [
    "Adorable",
    "Beautiful",
    "Clean",
    "Drab",
    "Elegant",
    "Fancy",
    "Glamorous",
    "Handsome",
    "Long",
    "Magnificent",
    "Plain",
    "Quaint",
    "Sparkling",
    "Ugliest",
    "Unsightly",
    "Angry",
    "Bewildered",
    "Clumsy",
    "Defeated",
    "Embarrassed",
    "Fierce",
    "Grumpy",
    "Helpless",
    "Itchy",
    "Jealous",
    "Lazy",
    "Mysterious",
    "Nervous",
    "Obnoxious",
    "Panicky",
    "Repulsive",
    "Scary",
    "Uptight",
    "Worried"
  ];

  const planets = [
    "Ahch-To",
    "Alderaan",
    "Anoat",
    "Atollon",
    "Bespin",
    "Corellia",
    "Coruscant",
    "D'Qar",
    "Dagobah",
    "Dantooine",
    "Dathomir",
    "Devaron",
    "Endor",
    "Felucia",
    "Geonosis",
    "Hosnian Prime",
    "Hoth",
    "Ilum",
    "Iridonia",
    "Jakku",
    "Jedha",
    "Kamino",
    "Kashyyyk",
    "Kessel",
    "Lothal",
    "Malachor",
    "Malastare",
    "Mandalore",
    "Maridun",
    "Calamari",
    "Moraband",
    "Mortis",
    "Mustafar",
    "Mygeeto",
    "Naboo",
    "Hutta",
    "Onderon",
    "Rishi",
    "Rodia",
    "Ruusan",
    "Ryloth",
    "Scarif",
    "Shili",
    "Starkiller",
    "Sullust",
    "Takodana",
    "Tatooine",
    "Toydaria",
    "Trandosha",
    "Umbara",
    "Utapau",
    "Yavin"
  ];

  const species = [
    "Amanin",
    "Anzati",
    "Aqualish",
    "Arachnor",
    "Arcona",
    "Arkanian",
    "Askajian",
    "Assembler",
    "Bantha",
    "Barabel",
    "Bimm",
    "Bith",
    "Blood Carver",
    "Bothan",
    "Caamasi",
    "Chadra-Fan",
    "Chevin",
    "Chiss",
    "Codru-Ji",
    "Coway",
    "Dewback",
    "Dianoga",
    "Dinko",
    "Drall",
    "Dressellian",
    "Droch",
    "Drovian",
    "Dug",
    "Duros",
    "Elom",
    "Elomin",
    "Spyder",
    "Ewok",
    "Exogorth",
    "Falleen",
    "Fia",
    "Firrerreo",
    "Gamorrean",
    "Gand",
    "Gank",
    "Givin",
    "Gotal",
    "Gran",
    "Gundark",
    "Gungan",
    "Hawk-bat",
    "H'nemthe",
    "Ho'Din",
    "Howlrunner",
    "Hssiss",
    "Hutt",
    "Ishi Tib",
    "Ithorian",
    "Ixll",
    "Jawa",
    "Jenet",
    "Kamarian",
    "Khommite",
    "Kitonak",
    "Klatooinian",
    "Ape-Lizard",
    "Dragon",
    "Kubaz",
    "Kurtzen",
    "Lorrdian",
    "Massassi",
    "Melodie",
    "Mimbanite",
    "Calamari",
    "Mrlssi",
    "Myneyrsh",
    "Mynock",
    "Neek",
    "Nerf",
    "Neti",
    "Nikto",
    "Noghri",
    "Ortolan",
    "Oswaft",
    "Pa'lowick",
    "Phindian",
    "Piranha",
    "Beetle",
    "Priapulin",
    "Psadan",
    "Pterosaur",
    "Purella",
    "Pydyrian",
    "Quarren",
    "Ranat",
    "Rancor",
    "Rishii",
    "Rodian",
    "Ronto",
    "Ruurian",
    "Sarlacc",
    "Selonian",
    "Shi'ido",
    "Slashrat",
    "Sluissi",
    "Ssi-ruu",
    "Sullustan",
    "Talz",
    "Tauntaun",
    "Taurill",
    "Thernbee",
    "Tin-Dwarf",
    "T'landa Til",
    "Togorian",
    "Togruta",
    "Toka",
    "Toydarian",
    "Trandoshan",
    "Trianii",
    "Raider",
    "Twi'lek",
    "Tynnan",
    "Ugnaught",
    "Blob",
    "Verpine",
    "Vor",
    "Vornskr",
    "Vratix",
    "Wampa",
    "Weequay",
    "Whiphid",
    "Womp Rat",
    "Wookiee",
    "Yaka",
    "Yarkora",
    "Yevetha",
    "Ysalamiri",
    "Amphistaff",
    "Coralskipper",
    "Dovin Basal",
    "Gnullith",
    "Yammosk",
    "Yuzzem",
    "Yuzzum",
    "Zeltron"
  ];

  return `${rando(adjectives)} ${rando(planets)} ${rando(species)}`;
};
